### ISSUE TITLE
Log to console without a file

### ISSUE THREAD

**Issue by msamblanet** [adpushup/woodlot#13]
If I attempt to configure woodlot to log to console and provide no streams, it logs the following message and does not finish initializing:

```woodlot[warning]: Please provide at least one valid file stream to start logging. More info here - https://github.com/adpushup/woodlot```

Based on a scan of the code this seems intentional but I have use cases where I do not need to log to a file (the stdout is collected and maintained) and in some cases (namely during dev) would like to preserve the console formatting...

I can workaround with a noop stream but based on scanning the code, it still formats the log to write to a file and then does nothing with it...

Would you be open to a PR to allow no streams to be specified if the console output is enabled?

**Comment by AnilAdPushup** [comment]
@msamblanet Please do, PRs are most welcome.

**Comment by ArunMichaelDsouza** [comment]
PR has been merged and the changes have been released with [v3.3.3](https://github.com/adpushup/woodlot/releases/tag/v3.3.3).
