### ISSUE TITLE
Logging json format as one-line compact string

### ISSUE THREAD

**Issue by sirius226** [adpushup/woodlot#7]
Hi, is there a way for json format logger to log as one-line compact string? 

It seems in utils.js all falsy values for spacing will be replaced by default value:
`spacing = spacing || constants.DEFAULT_JSON_SPACING;`

Could we support `spacing = 0` as compact string flag or add another option `compact: true/false`?

**Comment by ArunMichaelDsouza** [comment]
Good idea, support for this option can be added. I'll pick it up as soon as I get free. If you want to submit a PR, that would be great as well!

**Comment by sirius226** [comment]
Thanks @ArunMichaelDsouza , I can submit a PR

**Comment by ArunMichaelDsouza** [comment]
@sirius226 that's great!

**Comment by ArunMichaelDsouza** [comment]
This feature has been released in [v3.2.7](https://www.npmjs.com/package/woodlot/v/3.2.7).
